# .github/workflows/update-gtfs.yml
name: Update GTFS Static

on:
  schedule:
    - cron: '30 22 * * *'  # vers 00h30 à Paris en heure d'été
    - cron: '30 2 * * *'   # seconde passe de sécurité dans la nuit
  workflow_dispatch:
  push:
    paths:
      - 'script/update-gtfs.py'
      - '.github/workflows/update-gtfs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas requests
      - name: Run update script
        run: python script/update-gtfs.py
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add static/horaires_export.json
          git diff --cached --quiet || git commit -m "🔄 Mise à jour GTFS"
          git push
