# .github/workflows/update-gtfs.yml
name: Update GTFS Static

on:
  schedule:
    - cron: '30 3 * * *'  # tous les jours à 03h30
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas requests
      - name: Run update script
        run: python script/update-gtfs.py
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add static/horaires_export.json
          git commit -m "🔄 Mise à jour GTFS"
          git push
